#!/bin/bash

[[ -n $1 ]] && cd $1
RG_DEFAULT_COMMAND="rg -i -l --no-require-git --hidden"

selected=$(
FZF_DEFAULT_COMMAND="rg --files" fzf \
	-m \
	-e \
	--ansi \
	--disabled \
	--reverse \
	--bind "ctrl-a:select-all" \
	--bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
	--preview "rg -i --pretty --context 2 {q} {}" | cut -d":" -f1,2
)

[[ -n $selected ]] && vim $selected
