#!/bin/bash

while [ "$1" != "" ]; do
  case $1 in
    --single | -s)
      if (xrandr --output DP-2 --off --output DP-1 --off); then
        xrandr --output DP-2 --off
      else
        xrandr --output DP-2 --auto
      fi
      ;;
    --dual | -d)
      if (xrandr --auto --output DP-1 --primary --mode 3840x2160 --right-of DP-0); then
        xrandr --output DP-2 --off
      else
        xrandr --output DP-2 --auto
      fi
      ;;
    --integrated | -i)
      xrandr --output DP-2 --auto
      xrandr --output DP-1 --off --output DP-0 --off
      ;;
    ?)
      echo "script usage: [--single | -s] [-dual | -d] " >&2
      exit 1
      ;;
  esac
  shift
done
